import LeanDag.Common.History
import Mathlib.Algebra.Order.BigOperators.Group.Finset

/-!
# The acceptance rule, and view size from history size

`dos-equivocation-and-growth.md` §2, results D1-D4. A correct validator
accepts at most one block per validator at its latest round `A`, and its
view is the causal history of what it accepts. The point of the file is
`|V| ≤ (3f+1) · max |H(b)|` (D2), unconditional on the DoS condition,
synchrony or correctness, which reduces a bound on view size to a bound
on history size.
-/

namespace LeanDag

variable {Validator : Type*} [Fintype Validator] [DecidableEq Validator]
variable [F : Faults Validator]
variable {BlockId : Type*} [DecidableEq BlockId] {Payload : Type*}
variable {U : BlockUniverse Validator BlockId Payload}
variable {A A' : Finset BlockId} {b : BlockId} {m n n' : ℕ}

/-- What a validator has accepted at round `n`: real blocks of that round,
at most one per author. -/
structure Accepted (U : BlockUniverse Validator BlockId Payload)
    (A : Finset BlockId) (n : ℕ) : Prop where
  /-- Only real blocks are accepted. -/
  subset_ids : A ⊆ U.ids
  /-- One round: the frontier. -/
  round_eq : ∀ i ∈ A, (U.block i).round = n
  /-- At most one block per author — the rule. -/
  inj : ∀ i ∈ A, ∀ j ∈ A, (U.block i).creator = (U.block j).creator → i = j

omit [DecidableEq BlockId] in
/-- One block per author out of the `n` validators. -/
theorem Accepted.card_le (h : Accepted U A n) : A.card ≤ Fintype.card Validator := by
  have himg : (A.image (fun i => (U.block i).creator)).card = A.card :=
    Finset.card_image_of_injOn fun i hi j hj hij => h.inj i hi j hj hij
  rw [← himg]
  exact Finset.card_le_univ _

/-- **D1.** The view an accepted set generates: the union of the histories
of what it accepted, downward closed by transitivity of `Reaches`. -/
def View.ofAccepted (h : Accepted U A n) : View Validator BlockId Payload U where
  ids := A.biUnion (history U)
  subset_ids := by
    intro i hi
    obtain ⟨a, ha, hia⟩ := Finset.mem_biUnion.mp hi
    exact history_subset_ids (h.subset_ids ha) hia
  complete := by
    intro i hi j hj
    obtain ⟨a, ha, hia⟩ := Finset.mem_biUnion.mp hi
    have ha_ids : a ∈ U.ids := h.subset_ids ha
    refine Finset.mem_biUnion.mpr ⟨a, ha, ?_⟩
    exact (mem_history_iff ha_ids).mpr
      (((mem_history_iff ha_ids).mp hia).trans (Reaches.single hj))

@[simp]
theorem View.mem_ofAccepted (h : Accepted U A n) {i : BlockId} :
    i ∈ (View.ofAccepted h).ids ↔ ∃ a ∈ A, i ∈ history U a :=
  Finset.mem_biUnion

/-- **D2.** A view generated by an accepted set is at most `3f+1` histories
wide, unconditionally. -/
theorem View.card_ofAccepted_le (h : Accepted U A n)
    (hm : ∀ a ∈ A, (history U a).card ≤ m) :
    (View.ofAccepted h).ids.card ≤ (Fintype.card Validator) * m :=
  calc (View.ofAccepted h).ids.card
      ≤ ∑ a ∈ A, (history U a).card := Finset.card_biUnion_le
    _ ≤ ∑ _a ∈ A, m := Finset.sum_le_sum hm
    _ = A.card * m := Finset.sum_const_nat fun _ _ => rfl
    _ ≤ (Fintype.card Validator) * m := Nat.mul_le_mul_right m h.card_le

/-! ## D3 — the sharp form: referencing everything accepted, the view and
the history of the next block differ by that block alone. -/

/-- The view generated by `b`'s references is `b`'s history, less `b`. -/
theorem history_eq_insert_ofAccepted (h : Accepted U A n) (hb : b ∈ U.ids)
    (hrefs : (U.block b).refs = A) :
    history U b = insert b (View.ofAccepted h).ids := by
  ext i
  rw [mem_history_succ_iff hb, Finset.mem_insert, View.mem_ofAccepted, hrefs]

/-- A block never lies in the view its own references generate. -/
theorem notMem_ofAccepted_self (h : Accepted U A n) (hb : b ∈ U.ids)
    (hrefs : (U.block b).refs = A) : b ∉ (View.ofAccepted h).ids := by
  intro hmem
  obtain ⟨a, ha, hba⟩ := (View.mem_ofAccepted h).mp hmem
  have ha_refs : a ∈ (U.block b).refs := by rw [hrefs]; exact ha
  have h1 : (U.block a).round + 1 = (U.block b).round := U.round_of_mem_refs hb ha_refs
  have h2 := round_le_of_mem_history (h.subset_ids ha) hba
  omega

/-- **D3.** `|V| = |H(b)| - 1`, stated additively, when the validator
references everything it accepted. -/
theorem View.card_ofAccepted_add_one (h : Accepted U A n) (hb : b ∈ U.ids)
    (hrefs : (U.block b).refs = A) :
    (View.ofAccepted h).ids.card + 1 = (history U b).card := by
  rw [history_eq_insert_ofAccepted h hb hrefs,
    Finset.card_insert_of_notMem (notMem_ofAccepted_self h hb hrefs)]

/-! ## D4 — generated views grow: a later frontier covers an earlier one
once it reaches it, and retaining more only grows the view. -/

/-- **D4.** If everything accepted before is reachable from something
accepted now, the view has only grown. -/
theorem View.ofAccepted_subset (h : Accepted U A n) (h' : Accepted U A' n')
    (hcover : ∀ a ∈ A, ∃ a' ∈ A', Reaches U a' a) :
    (View.ofAccepted h).ids ⊆ (View.ofAccepted h').ids := by
  intro i hi
  obtain ⟨a, ha, hia⟩ := (View.mem_ofAccepted h).mp hi
  obtain ⟨a', ha', hreach⟩ := hcover a ha
  exact (View.mem_ofAccepted h').mpr
    ⟨a', ha', history_subset_of_reaches (h'.subset_ids ha') hreach hia⟩

/-- The form self-reference supplies. -/
theorem View.ofAccepted_subset_of_refs (h : Accepted U A n) (h' : Accepted U A' n')
    (hb : b ∈ A') (hA : A ⊆ (U.block b).refs) :
    (View.ofAccepted h).ids ⊆ (View.ofAccepted h').ids :=
  View.ofAccepted_subset h h' fun _a ha => ⟨b, hb, Reaches.single (hA ha)⟩

/-- **Exclusion governs what you reference, not what you retain.** -/
theorem View.ofAccepted_mono (h : Accepted U A n) (h' : Accepted U A' n')
    (hsub : A ⊆ A') : (View.ofAccepted h).ids ⊆ (View.ofAccepted h').ids :=
  View.ofAccepted_subset h h' fun a ha => ⟨a, hsub ha, Reaches.refl⟩

end LeanDag
