import LeanDag.History
import Mathlib.Algebra.Order.BigOperators.Group.Finset

/-!
# The acceptance rule, and view size from history size

`dos-equivocation-and-growth.md` §2, results **D1**–**D4**.

The rule: *a correct validator accepts at most one block per validator at its
latest round, and its view is the causal history of what it accepts.*

The point of the file is one inequality — `|V| ≤ (3f+1) · max |H(b)|` (D2) —
which reduces the DoS question about **view size** to a question about
**history size**, where the protection condition can act. Everything else is
scaffolding for it, and none of it needs the condition, synchrony, or
correctness: D2 is unconditional.

Three things had to be got right, and each is a numbered result:

* **D1** — the generated view really is a `View`. Downward closure is free,
  because a union of causal histories is downward closed. So the rule lands
  *inside* the existing model rather than beside it.
* **D3** — when the validator references everything it accepted, its view is
  exactly the history of the block it is about to build, and the factor `3f+1`
  disappears. This is the ordinary case; the exposure clause of the DoS
  condition is what can break it, and then D2 is the operative bound.
* **D4** — generated views grow, provided the next frontier reaches what the
  last one accepted. Self-reference is what supplies that in practice, and
  `ofAccepted_mono` is the other half: **exclusion governs what you reference,
  not what you retain.**

`A` is the *frontier* — one round. Earlier rounds are not accepted separately;
they enter the view inside the histories, which is what makes `|A| ≤ 3f+1`
rather than `(3f+1)(r+1)`. §4 gives `A` a home in the delivery
layer, where it is forced for an entirely different reason.
-/

namespace LeanDag

variable {Validator : Type*} [Fintype Validator] [DecidableEq Validator]
variable [F : Faults Validator]
variable {BlockId : Type*} [DecidableEq BlockId] {Payload : Type*}
variable {U : BlockUniverse Validator BlockId Payload}
variable {A A' : Finset BlockId} {b : BlockId} {m n n' : ℕ}

/-- What a validator has accepted at round `n`: real blocks of that round, at
most one per author.

The injectivity field is the acceptance rule, and it is the only one D2 uses —
the round field is what makes `A` a *frontier* rather than an accumulation, and
is used by D3. -/
structure Accepted (U : BlockUniverse Validator BlockId Payload)
    (A : Finset BlockId) (n : ℕ) : Prop where
  /-- Only real blocks are accepted. -/
  subset_ids : A ⊆ U.ids
  /-- One round: the frontier. -/
  round_eq : ∀ i ∈ A, (U.block i).round = n
  /-- At most one block per author — the rule. -/
  inj : ∀ i ∈ A, ∀ j ∈ A, (U.block i).creator = (U.block j).creator → i = j

omit [DecidableEq BlockId] in
/-- One block per author out of the `n` validators. This is the whole of what
the acceptance rule contributes. -/
theorem Accepted.card_le (h : Accepted U A n) : A.card ≤ Fintype.card Validator := by
  have himg : (A.image (fun i => (U.block i).creator)).card = A.card :=
    Finset.card_image_of_injOn fun i hi j hj hij => h.inj i hi j hj hij
  rw [← himg]
  exact Finset.card_le_univ _

/-- **D1 — the view an accepted set generates.**

That this typechecks *is* the result: `complete` is discharged by transitivity
of `Reaches`, so a union of causal histories is downward closed and no closure
obligation has to be met by hand. -/
def View.ofAccepted (h : Accepted U A n) : View Validator BlockId Payload U where
  ids := A.biUnion (history U)
  subset_ids := by
    intro i hi
    obtain ⟨a, ha, hia⟩ := Finset.mem_biUnion.mp hi
    exact history_subset_ids (h.subset_ids ha) hia
  complete := by
    intro i hi j hj
    obtain ⟨a, ha, hia⟩ := Finset.mem_biUnion.mp hi
    have ha_ids : a ∈ U.ids := h.subset_ids ha
    refine Finset.mem_biUnion.mpr ⟨a, ha, ?_⟩
    exact (mem_history_iff ha_ids).mpr
      (((mem_history_iff ha_ids).mp hia).trans (Reaches.single hj))

@[simp]
theorem View.mem_ofAccepted (h : Accepted U A n) {i : BlockId} :
    i ∈ (View.ofAccepted h).ids ↔ ∃ a ∈ A, i ∈ history U a :=
  Finset.mem_biUnion

/-- **D2 — the bridge.** A view generated by an accepted set is at most `3f+1`
histories wide.

Unconditional: no DoS condition, no synchrony, no correctness hypothesis. This
is what turns every bound on `|H(b)|` into a bound on what a validator
stores. -/
theorem View.card_ofAccepted_le (h : Accepted U A n)
    (hm : ∀ a ∈ A, (history U a).card ≤ m) :
    (View.ofAccepted h).ids.card ≤ (Fintype.card Validator) * m :=
  calc (View.ofAccepted h).ids.card
      ≤ ∑ a ∈ A, (history U a).card := Finset.card_biUnion_le
    _ ≤ ∑ _a ∈ A, m := Finset.sum_le_sum hm
    _ = A.card * m := Finset.sum_const_nat fun _ _ => rfl
    _ ≤ (Fintype.card Validator) * m := Nat.mul_le_mul_right m h.card_le

/-! ## D3 — the sharp form

When the validator references everything it accepted, the view and the history
of its next block differ by that block alone. -/

/-- The view generated by `b`'s references is `b`'s history, less `b`. -/
theorem history_eq_insert_ofAccepted (h : Accepted U A n) (hb : b ∈ U.ids)
    (hrefs : (U.block b).refs = A) :
    history U b = insert b (View.ofAccepted h).ids := by
  ext i
  rw [mem_history_succ_iff hb, Finset.mem_insert, View.mem_ofAccepted, hrefs]

/-- A block is never inside the view its own references generate: everything
there sits a round lower. -/
theorem notMem_ofAccepted_self (h : Accepted U A n) (hb : b ∈ U.ids)
    (hrefs : (U.block b).refs = A) : b ∉ (View.ofAccepted h).ids := by
  intro hmem
  obtain ⟨a, ha, hba⟩ := (View.mem_ofAccepted h).mp hmem
  have ha_refs : a ∈ (U.block b).refs := by rw [hrefs]; exact ha
  have h1 : (U.block a).round + 1 = (U.block b).round := U.round_of_mem_refs hb ha_refs
  have h2 := round_le_of_mem_history (h.subset_ids ha) hba
  omega

/-- **D3.** `|V| = |H(b)| - 1`, stated additively.

Note what it takes: `refs = A`, the validator referencing *everything* it
accepted. The DoS condition's exposure clause is exactly what can make `refs`
a proper subset, and then this fails in the unhelpful direction — the dropped
block is still retained — so D2 is the bound that survives. -/
theorem View.card_ofAccepted_add_one (h : Accepted U A n) (hb : b ∈ U.ids)
    (hrefs : (U.block b).refs = A) :
    (View.ofAccepted h).ids.card + 1 = (history U b).card := by
  rw [history_eq_insert_ofAccepted h hb hrefs,
    Finset.card_insert_of_notMem (notMem_ofAccepted_self h hb hrefs)]

/-! ## D4 — generated views grow

Two halves. `ofAccepted_subset` is the general statement: a later frontier
covers an earlier one as soon as it *reaches* it, which is what referencing
your own previous block supplies. `ofAccepted_mono` is the other half — a
validator that merely retains more sees more, whatever it goes on to
reference. -/

/-- **D4.** If everything accepted before is reachable from something accepted
now, the view has only grown. -/
theorem View.ofAccepted_subset (h : Accepted U A n) (h' : Accepted U A' n')
    (hcover : ∀ a ∈ A, ∃ a' ∈ A', Reaches U a' a) :
    (View.ofAccepted h).ids ⊆ (View.ofAccepted h').ids := by
  intro i hi
  obtain ⟨a, ha, hia⟩ := (View.mem_ofAccepted h).mp hi
  obtain ⟨a', ha', hreach⟩ := hcover a ha
  exact (View.mem_ofAccepted h').mpr
    ⟨a', ha', history_subset_of_reaches (h'.subset_ids ha') hreach hia⟩

/-- The form self-reference supplies: `v`'s next block is accepted at the next
round and references everything `v` accepted at this one. -/
theorem View.ofAccepted_subset_of_refs (h : Accepted U A n) (h' : Accepted U A' n')
    (hb : b ∈ A') (hA : A ⊆ (U.block b).refs) :
    (View.ofAccepted h).ids ⊆ (View.ofAccepted h').ids :=
  View.ofAccepted_subset h h' fun _a ha => ⟨b, hb, Reaches.single (hA ha)⟩

/-- **Exclusion governs what you reference, not what you retain.** Retaining
more is monotone on its own, so a validator that keeps a block whose author it
has since excluded does not lose the decisions that block supported. -/
theorem View.ofAccepted_mono (h : Accepted U A n) (h' : Accepted U A' n')
    (hsub : A ⊆ A') : (View.ofAccepted h).ids ⊆ (View.ofAccepted h').ids :=
  View.ofAccepted_subset h h' fun a ha => ⟨a, hsub ha, Reaches.refl⟩

end LeanDag
